// import '@/assets/css/bootstrap.min.css'
import '@/assets/css/responsive.css'
import '@/assets/css/style.css'
import '@/assets/css/custom.css'
import '@fortawesome/fontawesome-svg-core/styles.css'
import StyledComponentsRegistry from '@/styles/styleRegistry'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import { ConfigProvider } from 'antd'
import React from 'react'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

const primaryRed = '#D8002C'
const primaryWhite = '#FFFFFF'

const theme = {
    token: {
        fontSize: 16,
        colorPrimary: primaryRed,
        borderRadius: 0,
        colorLink: primaryRed,
        controlHeight: 40,
        colorPrimaryBorder: '#4d8200',
    },
    components: {
        Input: {
            hoverBorderColor: primaryRed,
        },
        Button: {
            contentFontSize: 13,
            fontSize: 13,
            paddingBlock: 0,
            paddingInline: 24,
            paddingInlineLG: 48,
        },
        Tabs: {
            cardBg: 'rgba(33, 33, 32, 0.6)',
            cardGutter: 0,
            cardHeight: 40,
            cardPadding: '12px 28px',
            horizontalItemPadding: 48,
            lineWidth: 0,
            horizontalMargin: 0,
            horizontalItemMargin: '0px 24px',

            verticalItemMargin: '0 24px 0 0 ',
            colorBgContainer: primaryWhite,
            itemHoverColor: primaryWhite,
            itemActiveColor: primaryRed,
            itemColor: '#fff',
            colorPrimaryBorder: '#4d8200',
        },
    },
}

export default function RootLayout({ children }) {
    return (
        <html lang="hy">
            <body>
                <AntdRegistry>
                    <StyledComponentsRegistry>
                        <ConfigProvider theme={theme}>
                            {children}
                        </ConfigProvider>
                    </StyledComponentsRegistry>
                </AntdRegistry>
            </body>
        </html>
    )
}
